[package]
name = "middb-query"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
middb-core = { path = "../middb-core" }
sqlparser.workspace = true
parking_lot.workspace = true

[dev-dependencies]
tempfile = "3.0"
